[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[context]

  [context.deploy-preview]

    [context.deploy-preview.functions]

      [context.deploy-preview.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]